stages:
  - plan
  - destroy

terraform:
  stage: plan
  image: hashicorp/terraform:latest
  script:
    - terraform init
    - terraform validate
    - terraform plan -out=tfplan
  artifacts:
    paths:
      - tfplan

terraform_destroy:
  stage: destroy
  image: hashicorp/terraform:latest
  script:
    - terraform init
    - terraform destroy -auto-approve
  when: manual
